local items = {
	"yoyo",
	"amongus plushie",
	"birthday cake",
	"candy wrapper",
	"trash can",
	"dog",
	"crab",
	"bomb",
	"knife",
	"spoon",
	"dorito",
	"water bottle",
	"phone",
	"car",
	"half broken wooden crate",
	"bed",
	"firework",
	"xbox",
	"grain of sand",
	"metal pipe",
	"wooden board",
	"tree",
	"orange",
	"eggplant",
	"string",
	"dinosaur",
	"fish",
	"bucket",
	"lamp",
	"wires",
	"copper",
	"shattered glass pieces",
	"platinum coin",
	"gram of gold",
	"kilo of gold",
	"treasure chest",
	"shipping wreck",
	"cheetos",
	"empty pringles box",
	"bouncy balls",
	"8 ball",
	"glass cup",
	"pineapple",
	"anvil",
	"silver ring",
	"microphone",
	"table",
	"ok quality keyboard",
	"good quality mouse",
	"painting",
	"puzzle kit",
	"empty puzzle kit",
	"2 puzzle kits but the pieces are half lost and in chaos",
	"bubblegum machine",
	"minecraft diamond made of plastic",
	"toy gun",
	"shotgun",
	"50 ammo clip",
	"samsung phone charger",
	"broken ipad",
	"ritalin",
	"1Tb HDD",
	"empty computer case",
	"giftbox with books in it",
	"keys to a random house",
	"bad quality camera",
	"15 ft amongus plushie (very big)",
	"paper with random to do list",
	"fly swatter",
	"just one sausage",
	"griller",
	"8 pool table",
	"a random CPU",
	"GeForce RTX 3060 Ti",
	"wardrobe",
	"oven",
	"bread",
	"baguette",
	"plastic bag",
	"a bit of silicon",
	"dry ice",
	"ice cube mold",
	"melted strawberry flavored ice cream",
	"empty chocolate bar (just the packet)",
	"butterfly",
	"tiger",
	"bow",
	"3 arrows",
	"sand castle mold",
	"electricity plug",
	"toy zombie",
	"blue sponge",
	"lightbulb",
	"red LED",
	"random pair of yellow socks",
	"pink underwear",
	"half used toilet roll",
	"toilet roll",
	"all used toilet roll",
	"lit candle",
	"orange candle thats half melted and unlit",
	"random lego pieces",
	"football thats cut in half from the center",
	"football",
	"a singular piece of brown hair",
	"a yellow wig",
	"just a strawberry",
	"just 1 piece of snowflake",
	"just one bullet",
	"the most bright light ever",
	"giant megaphone (bigger then the average human)",
	"megaphone",
	"scarf",
	"scarf made of amongus texture",
	"shirt with memes",
	"matching amongus pants and shirt",
	"random ripe pants thats 5 years old and has been used by 12 people",
	"sewing machine",
	"phone case",
	"27 brown grass blades",
	"gold crown",
	"diamond crown",
	"crown made of literally stone and painted manually",
	"red paint bucket",
	"half empty blue paint bucket",
	"a white queen from chess",
	"a black bishop from chess",
	"an entire chess board missing a white queen and a black bishop",
	"20 pieces of kings from chess with all the different colors like red, yellow, pink, blue, black...",
	"a random bone",
	"the fossil of a dragon",
	"just one slipper",
	"a pair of slippers",
	"a pair of shoes but there's spikes inside",
	"cactus",
	"timed bomb",
	"police car that has a siren that cannot be turned off",
	"blue and pink boxing gloves",
	"one brown boxing glove",
	"a very bad quality wallet",
	"a black wallet",
	"bandaid",
	"cigarette that already has been smoken",
	"a fully working gun (Glock 17)",
	"a P90 with no ammo",
	"RGB M16 with 500 full ammo clips",
	"dream mask",
	"a random drama mask",
	"a whole entire theatre",
	"just one theatre seat",
	"a coffin",
	"a coffin with someone alive inside locked",
	"a CD with cheetos's voice saying uhhh repeating",
	"a very shiny red stone",
	"a rock",
	"just one grain of wheat",
	"50 sugar cubes",
	"eaten sugar cube",
	"green leaf",
	"a math textbook",
	"SAT Exam Papers",
	"npesta's kenos mouse",
	"npesta's streaming setup package",
	"a panda keychain",
	"a working rocket launcher keychain",
	"RPG",
	"A giant salt rock",
	"Pillow",
	"A singular bird feather",
	"poop",
	"clogged toilet",
	"12th grade geometry book",
	"a random kid's toy",
	"a geometry pieces kid's toy package where they insert like pieces into holes",
	"a chess board made of valuable materials like gold and diamond etc (random materials tho)",
	"a USB stick with only Oscilattion from Deepwoken as an MP3 inside of it",
	"an empty USB Stick",
	"a USB stick with 1Tb of random videos and mp3s inside",
	"a tree log",
	"2 branches",
	"battle axe",
	"hero blade of fire but irl model (very cool)",
	"katana",
	"broken katana",
	"sword",
	"bent sword thats in the shape of a U (the blade part)",
	"fang of gilgamesh in real life",
	"donut model",
	"literally a road just appears",
	"singular piece of cloth",
	"mexican hat",
	"violet colored tiny fanny pack made of just pure spider silk",
	"mosquito that follows you forever and is invincible",
	"a singular blade of grass",
	"salmon",
	"red fish",
	"blue fish",
	"yellow fish",
	"green fish",
	"a mcdonalds burger",
	"milkshake",
	"someone's saliva in a plastic bottle (like full of it)",
	"a whole rock mountain",
	"campfire",
	"flint",
	"steel bar",
	"literally an in real life nether portal (doesnt work tho)",
	"e-sports quality computer with all specs like keyboard, mouse and everything included",
	"a packet of random chips full of random chip brands",
	"rainbow magic carpet that can fly",
	"grey wall",
	"pink tree",
	"whole rtoc lore in a book",
	"a burning piano",
	"a sad bacon hair from roblox irl poor asking for money",
	"lava obby",
	"a trillion dollars",
	"stone mask from jojo (doesn't make you a vampfire)",
	"screwdriver",
	"a screw packets",
	"a flag of ukraine",
	"an entire american gunshop",
	"a moon made of wood and painted, its size is bigger than an average apartment building",
	"amongus character, alive, in real life [SUS! SUS!]",
	"a guitar with 2 strings not on it (broken)",
	"a good quality electric guitar",
	"a whole piano that's 5 times the size of a normal piano",
	"just like 5 grains of protein powder",
	"an SDD with 100MB of storage lol",
	"a big red 3D sign that says L",
	"lollipop",
	"a very hot steel ball that won't cool down",
	"a huge bucket full of honey",
	"a page up keycap",
	"spacebar",
	"the L keycap",
	"a mechanical keyboard with half the keycaps missing",
	"an anchor",
	"a packet of cheetos",
	"vitamin D pills",
	"nutella bread",
	"YOUR passport that you lost 7 years ago",
	"a roblox toy",
	"a roblox toy code but half of the code is missing",
	"a 27 inch 1440p monitor 40 hz",
	"10 inch 144p 2 hz monitor",
	"a monitor that doesn't work it's just toy",
	"AN ENTIRE CHINESE MAN",
	"THE ENTIRE COMPANY OF ROBLOX JUST SPAWNS IN",
	"a keyboard made of only the 'alt' and 'F4' keys",
	"a souvenir from singapore",
	"a lollipop that's half broken",
	"a lollipop without the stick",
	"just a stick",
	"a handful of spaghetti",
	"a red plastic circle",
	"a big dark blue metal circle",
	"just ice. one ice. i dont know.",
	"1 cm^3 of ice",
	"a big boulder",
	"vitamin A pills",
	"all color amongus plushie package",
	"20 cents from europe",
	"a randomly shaped empty plastic package",
	"a giant box for the best PC ever, but it's empty. You just get the box",
	"a trackpad but just the trackpad",
	"a core i7 1st generation",
	"a core i50 78th generation (from the future)",
	"just a floor made out of wood spawns in",
	"displayport cable",
	"HDMI cable",
	"Mini displayport cable",
	"A LAPTOP WITH ONLY THE GD LEVEL 'CABLE' IN IT",
	"the entire eiffel tower",
	"a giant red LED ? sign",
	"the entire statue of liberty",
	"a photo of niko as a baby",
	"a baby doll",
	"a photo of red as a child",
	"2 photos of red one with red having a beard and one without the beard",
	"all language textbooks in the world",
	"the flag of sweden",
	"the flag of turkey",
	"a flag but theres amonguses in it",
	"the entirety of r/place in reddit in plastic blocks that are 8 cubic centimeters per pixel",
	"9 thousand flies",
	"a random person's divorce papers",
	"a 9x9 rubik's cube",
	"a perfectly made no chance of popping 60x60 rubik's cube but it's connected to a timebomb that's set to 7 days and you gotta solve it",
	"a baton",
	"a bent baton",
	"a bent fork",
	"silver wires",
	"9000 cats",
	"a classic wooden chair with perfect polish",
	"chair.",
	"jake paul",
	"the ownership of VCR card",
	"bluetooth device is really cheap here (an indian man spawns with a shop repeating that to you until you buy something you can't leave [it's 5000$])",
	"the entire country of finland",
	"the entire country of russia",
	"the entire earth is yours now everyone dies",
	"depression potion",
	"antibabypillen",
	"a phone with very very broken screen",
	"a satellite radio station",
	"17000 koiraa",
	"a pill that teaches you all languages in the world but also disintegrates your legs (you don't know that tho)",
	"the finnish number sequence as pronounced by red on paper",
	"24 million empty sheets of paper",
	"a fax machine that doesn't work",
	"a fax machine that works :thumbs up:",
	"a block of gravel perfectly in shape from minecraft",
	"5 hong kong dollars",
	"your bills but their price is multiplied by 10 [you must pay them]",
	"george washington",
	"samsung TV",
	"THE ENTIRE RTOC IRL VERSION SPAWNS IN AND YOU GOTTA GO THROUGH ALL THE ADVENTURE AND BECOME THE PROPHECY",
	"the entirety of scp-3008 (good luck)",
	"an ikea you must go through with zombies in it",
	"an ikea you must go through but it is 20 times bigger than a normal ikea",
	"a washing machine",
	"an electrician",
	"an antique music player",
	"the gd level 'whitespace' on a usb stick",
	"that one piece of paper you threw in the trash seven years ago",
	"the Bank of America database servers",
	"a burning hot potato",
	"a ship",
	"the titanic in its current state",
	"the titan submersible in its current state",
	"a ps4 controller",
	"an xbox controller",
	"a sign for the small hill of Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu",
	"a sign for the small english village of Llanfair­pwllgwyngyll­gogery­chwyrn­drobwll­llan­tysilio­gogo­goch",
	"a sign for the finnish bog region of Äteritsiputeritsipuolilautatsijänkä",
	"This, is Elon Musk.",
	"a snotfish",
	"a great white shark",
	"a frog",
	"a frog plinko",
	"confidential cia documents",
	"a 700 watt power supply unit",
	"an all-in-one computer",
	"a cabinet",
	"a couch",
	"a very expensive queen-sized bed (that hasn't been paid in full, meaning that you have to pay the rest)",
	"your taxes that you evaded",
	"a tv remote",
	"the monopoly board game",
	"a 2000-piece puzzle",
	"a chicken",
	"a bottlecap",
	"a grey, silver-coated bottlecap with foam inside",
	"a cotton ball",
	"a ukulele",
	"a red ukulele",
	"a melon candy",
	"a random snowglobe",
	"a broken table",
	"the painting of mona lisa",
	"a random amount of dust",
	"tan curtains",
	"sand from your local beach",
	"a really old tv",
	"a really NEW tv",
	"the best imaginable tv but there's only one channel",
	"a whole book of empty pages, but one of the pages has the word 'yksi' on it",
	"a small bell",
	"a giant gong",
	"a giant chinese gong",
	"an image of your school",
	"a photo of your friends at school",
	"a carpet",
	"a carpet with 'j' written on it",
	"very dusty rug",
	"a glass weight scale",
	"your computer but in roblox",
	"a whiteboard with 'make money' written on it",
	"an empty lecture blackboard",
	"a blackboard full of complex math equations (there's also a bomb your way you must solve them)",
	"a book with the answers to the milennium prizes on it",
	"a very good rgb gaming chair 'he just has a good gaming chair bro'",
	"a computer with every single exploit downloaded on it",
	"a 1tb expansion drive",
	"a clay vase",
	"a glass vase",
	"a crab in the shape of amongus",
	"a shallot",
	"a sata cable",
	"nail clippers",
	"purple nail clippers",
	"tennis balls",
	"a glass vase with purple spiky flowers in it",
	"a table with insanely big wheels",
	"a random job application",
	"another one of this lucky block",
	"a random cow",
	"a cow that's 50x the size of a normal cow",
	"a trash can full of newspaper",
	"a newspaper from 1977",
	"a newspaper from 2001",
	"the world trade center",
	"a sniper rifle with autoaim",
	"a boeing 737",
	"a purple sniper rifle",
	"an airbus a320",
	"a gaming hunter rifle",
	"a gaming rgb hunter rifle 360",
	"a birthday cake made out of inedible ingredients",
	"a random membrane keyboard",
	"a packet of random pills",
	"a packet of random candy",
	"a bucket the size of an 5-story apartment building full of chocolate",
	"a bucket of milk",
	"a bucket of water",
	"a bucket of lava",
	"a whole volcano from iceland",
	"a whole barn",
	"a barn full of 5000 chickens",
	"a spawner from minecraft with a random passive mob in it",
	"a bucket of random seeds",
	"a plastic bottle full of pumpkin seeds",
	"a packet of apples",
	"a toy shoe",
	"a yellow toy shoe",
	"a yellow toy shoe with blue shoelaces",
	"a yellow toy shoe with blue shoelaces and an amongus image on it",
	"a yellow toy shoe with blue shoelaces, an amongus image on it, and wings",
	"a jetpack",
	"a jetpack with infinite fuel",
	"a jetpack with no fuel",
	"a whole private jet",
	"a whole private airplane",
	"ten buckets of aircraft fuel",
	"seven barrels of oil",
	"a thank you card",
	"a gorilla in a cage",
	"a girl whose mother put her in a cage",
	"basically a real life Primadon",
	"a working sound player that keeps playing the sound 'womp womp', is unstoppable, is unbreakable, and everyone can hear it (bro really said MaxRolloffDistance = 1000000)",
	"a golden candle",
	"a thick golden candle",
	"a piece of paper with a random adjective on it",
	"a piece of paper full of sentences with incorrect grammar",
	"a 1200-page book full of the word 'amongus'", --red you're really unfunny
	"a bottle of air",
	"a glass sphere",
	"a hollow glass sphere full of random gasses",
	"a 600-page book explaining the lore of Deepwoken deeply and thoroughly",
	"a book named '50 tips for compliment'",
	"a pair of fake nipples",
	"100 euros from europe",
	"100 pounds from the uk",
	"a real terraria Terra Blade",
	"a real terraria Terraspark Boots",
	"a pair of Terraspark Boots and the Terra Blade from terraria",
	"a whole in-real-life replica of 3d terraria that you have to beat (it's permadeath)"
}

local function sleep(n)
	if n > 0 then os.execute("ping -n " .. tonumber(n + 1) .. " localhost > NUL") end
end

local z = 0
while true do
	sleep(0.2)
	z = z + 1
	local randomNumber = math.random(1, #items)
	print("roll " .. tostring(z) .. ": " .. items[randomNumber])
end

--[[
	local z = 0
while wait(2) do
z = z + 1
local randomNumber = math.random(1, #items)
print("roll " .. tostring(z) .. ": " .. items[randomNumber])
end
]]
